add execute_command() wrapper function and refactor more errors

diff --git a/zxfer b/zxfer
--- a/zxfer
+++ b/zxfer
@@ -147,8 +147,8 @@ trailing_slash=0
 
 LZFS=$(which zfs)
 RZFS=$LZFS
-# used by the copy_snap() functions
-cmd=""
+ssh_cmd="ssh"
+
 # default compression commands
 option_z_compress_cmd="zstd -3"
 option_z_decompress_cmd="zstd -d"
@@ -243,7 +243,7 @@ init_variables() {
 
   # prepend ssh to option_O_rigin if not already there
   if [ "$option_O_rigin" != "" ]; then
-    get_os "ssh $option_O_rigin"
+    get_os "$ssh_cmd $option_O_rigin"
   else
     get_os ""
   fi
@@ -251,7 +251,7 @@ init_variables() {
   source_os="$output_os"
 
   if [ $option_e_restore_property_mode -eq 1 ]; then
-    LCAT=$(ssh ${option_O_rigin} which cat)
+    LCAT=$(${ssh_cmd} ${option_O_rigin} which cat)
   fi
 
   if [ $option_S -eq 1 ]; then
@@ -293,9 +293,10 @@ EOT
 # Function to handle errors
 throw_error() {
   local msg=$1
+  exit_status=$2 || 1
   echo $msg
   beep
-  exit 1
+  exit $exit_status
 }
 
 throw_usage_error() {
@@ -304,6 +305,25 @@ throw_usage_error() {
   usage
   beep
   exit 1
+}
+
+execute_command() {
+  cmd=$1
+  is_continue_on_fail=$2
+
+  if [ $option_n_dryrun -eq 1 ]; then
+    echov "Dry run: $cmd"
+    return
+  fi
+
+  echov $cmd
+  if [ $is_continue_on_fail -eq 1 ]; then
+    eval $cmd || {
+      echo "Non-critical error when executing command. Continuing."
+    }
+  else
+    eval $cmd || throw_error "Error when executing command."
+  fi
 }
 
 #
@@ -411,7 +431,7 @@ consistency_check() {
 # Takes $snapshot, $dest, $lastsnap
 #
 # Function to handle zfs send/receive with progress dialog
-set_zfs_send_receive_with_progress_cmd() {
+zfs_send_receive_with_progress() {
   local snapshot=$1
   local dest=$2
   local prevsnap=$3
@@ -420,7 +440,7 @@ set_zfs_send_receive_with_progress_cmd() {
 
   # calc size estimate
   if [ "$option_O_rigin" != "" ]; then
-    LZFS="ssh $option_O_rigin $LZFS"
+    LZFS="$ssh_cmd $option_O_rigin $LZFS"
   fi
 
   SIZE_DATASET=$($LZFS send -nPv "$1" 2>&1) || throw_error "Error calculating estimate: $SIZE_DATASET"
@@ -442,14 +462,14 @@ set_zfs_send_receive_with_progress_cmd() {
 
   # wrap the send command in double quotes so that it can be passed to ssh
   if [ "$option_O_rigin" != "" ]; then
-    send_cmd="ssh $option_O_rigin \"$send_cmd\" "
+    send_cmd="$ssh_cmd $option_O_rigin \"$send_cmd\" "
   fi
 
-  cmd="$send_cmd | $recv_cmd"
+  execute_command "$send_cmd | $recv_cmd"
 }
 
 # Function to handle zfs send/receive
-set_zfs_send_receive_cmd() {
+zfs_send_receive() {
   local snapshot=$1
   local dest=$2
   local prevsnap=$3
@@ -459,20 +479,20 @@ set_zfs_send_receive_cmd() {
   if [ -z "$prevsnap" ]; then
     send_cmd="/sbin/zfs send $snapshot"
   else
-    send_cmd="/sbin/zfs send -i $prevsnap $snapshot "
+    send_cmd="/sbin/zfs send -i $prevsnap $snapshot"
   fi
   recv_cmd="$RZFS receive $option_F $dest"
 
   # wrap the send command in double quotes so that it can be passed to ssh
   if [ "$option_O_rigin" != "" ]; then
     if [ $option_z_compress -eq 0 ]; then
-      send_cmd="ssh $option_O_rigin \"$send_cmd\" "
+      send_cmd="$ssh_cmd $option_O_rigin \"$send_cmd\""
     else
-      send_cmd="ssh $option_O_rigin \"$send_cmd | $option_z_compress_cmd\" | $option_z_decompress_cmd "
+      send_cmd="$ssh_cmd $option_O_rigin \"$send_cmd | $option_z_compress_cmd\" | $option_z_decompress_cmd"
     fi
   fi
 
-  cmd="$send_cmd | $recv_cmd"
+  execute_command "$send_cmd | $recv_cmd"
 }
 
 copy_snap() {
@@ -483,27 +503,14 @@ copy_snap() {
 
   # Check if the snapshot already exists
   if [ -n "$(echo "$rzfs_list_ho_s" | grep "^$dest/$copysrctail")" ]; then
-    echo "Snapshot $copysrc already exists at destination $copydest. Exiting function."
+    echov "Snapshot $copysrc already exists at destination $copydest. Exiting function."
     return
   fi
 
-  echov "Sending $copysrc to $copydest."
-  if [ "$copyprev" != "" ]; then
-    echov "  (incremental to $copyprev.)"
-  fi
-
-  # these functions will set the value of $cmd
   if [ "$option_D" != "" ]; then
-    set_zfs_send_receive_with_progress_cmd "$copysrc" "$copydest" "$copyprev"
+    zfs_send_receive_with_progress "$copysrc" "$copydest" "$copyprev"
   else
-    set_zfs_send_receive_cmd "$copysrc" "$copydest" "$copyprev"
-  fi
-
-  # cmd is now set
-  if [ "$option_n_dryrun" -eq 1 ]; then
-    echo $cmd
-  else
-    eval $cmd || throw_error "Error when zfs send/receiving."
+    zfs_send_receive "$copysrc" "$copydest" "$copyprev"
   fi
 }
 ## END copy_snap() and related functions
@@ -563,11 +570,7 @@ newsnap() {
     cmd="$LZFS snapshot $sourcefs@$snap"
   fi
 
-  if [ $option_n_dryrun -eq 0 ]; then
-    eval $cmd || throw_error "Error when snapshotting."
-  else
-    echo $cmd
-  fi
+  execute_command $cmd
 }
 
 #
@@ -662,14 +665,8 @@ inspect_delete_snap() {
     if [ $mark_snap_for_deletion = 1 -a $option_d -eq 1 ]; then
       echov "Destroying destination snapshot $dest_snap."
       cmd="$RZFS destroy $dest_snap"
-      if [ $option_n_dryrun -eq 0 ]; then
-        # A failed destroy is not a critical error, it is likely caused by
-        # a hold or a clone. Continue with the replication
-        eval $cmd ||
-          { echo "Error when zfs destroying."; }
-      else
-        echo $cmd
-      fi
+      # pass 1 to continue command if it fails
+      execute_command $cmd 1
     fi
   done
 
@@ -710,36 +707,24 @@ get_zfs_list() {
   initial_source=${initial_source%/}
 
   rzfs_list_ho_s=$($RZFS list -t filesystem,volume -Ho name -s creation) ||
-    {
-      echo "Failed to retrieve datasets from the destination"
-      exit 3
-    }
+    throw_error "Failed to retrieve datasets from the destination" 3
+
   lzfs_list_hr_s_snap=$($LZFS list -Hr -o name -s creation -t snapshot $initial_source) ||
-    {
-      echo "Failed to retrieve snapshots from the source"
-      exit 3
-    }
+    throw_error "Failed to retrieve snapshots from the source" 3
+
   # Note that for OpenSolaris compatibility, instead of using gtac
   # we will use ...| cat -n | sort -nr | cut -c 8-
   # gtac line
   lzfs_list_hr_S_snap=$(echo "$lzfs_list_hr_s_snap" | cat -n)
   lzfs_list_hr_S_snap=$(echo "$lzfs_list_hr_S_snap" | sort -nr | cut -c 8-)
   rzfs_list_hr_S_snap=$($RZFS list -Hr -o name -S creation -t snapshot $destination) ||
-    {
-      echo "Failed to retrieve snapshots from the destination"
-      exit 3
-    }
+    throw_error "Failed to retrieve snapshots from the destination" 3
 
   recursive_source_list=$($LZFS list -t filesystem,volume -Hr -o name "$initial_source") ||
-    {
-      echo "Failed to retrieve list of datasets from the source"
-      exit 3
-    }
+    throw_error "Failed to retrieve list of datasets from the source" 3
+
   recursive_dest_list=$($RZFS list -t filesystem,volume -Hr -o name "$destination") ||
-    {
-      echo "Failed to retrieve list of datasets from the destination"
-      exit 3
-    }
+    throw_error "Failed to retrieve list of datasets from the destination" 3
 
   # Exit if source not sound
   if [ "$recursive_source_list" = "" ]; then
@@ -1469,7 +1454,7 @@ $override_value=$override_source,"
 
   # This is where we actually create or modify the destination filesystem.
   # Is the destination absent? If so, just create with correct option list.
-  if [ "$dest_exist" -eq "0" ]; then
+  if [ "$dest_exist" = "0" ]; then
     if [ "$initial_source" = "$source" ]; then
       # as this is the initial source, we want to transfer all properties from
       # the source, overridden with option_o values as necessary
@@ -1956,7 +1941,7 @@ while getopts bBc:deE:f:Fg:hiI:klL:lmnN:o:O:pPPR:sST:u:Uv?:D:zZ: i; do
     option_o="$OPTARG"
     ;;
   O)
-    LZFS="ssh $OPTARG /sbin/zfs"
+    LZFS="$ssh_cmd $OPTARG /sbin/zfs"
     option_O_rigin="$OPTARG"
     ;;
   p)
@@ -1975,8 +1960,8 @@ while getopts bBc:deE:f:Fg:hiI:klL:lmnN:o:O:pPPR:sST:u:Uv?:D:zZ: i; do
     option_S=1
     ;;
   T)
-    RZFS="ssh $OPTARG /sbin/zfs"
-    option_T_arget="ssh $OPTARG "
+    RZFS="$ssh_cmd $OPTARG /sbin/zfs"
+    option_T_arget="$ssh_cmd $OPTARG "
     ;;
   u)
     option_u=1
